version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "syncronousApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2fhfgbgjnmzt"
s3_prefix = "syncronousApi"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
